### ISSUE TITLE
Error Python

### ISSUE THREAD

**Issue by dhelena5** [MSBilgin/EasyAHP#8]
When working with QGis version 3.28 the following message is displayed: 

2023-06-01T11:40:56     WARNING    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python/plugins\EasyAHP\easyAHP.py", line 258, in nextStep2
              self.tableMaker()
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python/plugins\EasyAHP\easyAHP.py", line 232, in tableMaker
              cellItem = QtGui.QTableWidgetItem()
             AttributeError: module 'qgis.PyQt.QtGui' has no attribute 'QTableWidgetItem'
 
What can I do? thanks

**Comment by Heed725** [comment]
Try using this plugin in Qgis 3 

[EasyAHP.zip](https://github.com/user-attachments/files/22676563/EasyAHP.zip)
